version: 2.1

orbs:
  docker: circleci/docker@2.0.3

jobs:
  build:
    docker:
      - image: cimg/node:current
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build .

workflows:
  workflow:
    jobs:
      - docker/hadolint
      - build