version: 2.1

orbs:
  docker: circleci/docker@2.0.3

workflows:
  workflow:
    jobs:
      - docker/publish:
          executor:
            name: docker/machine
            dlc: true
          lint-dockerfile: true
          docker-username: DOCKERHUB_USERNAME
          docker-password: DOCKERHUB_PASSWORD
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
