version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build .
